// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehyeqbbbiefocfbcjmtq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVoeWVxYmJiaWVmb2NmYmNqbXRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNjY5NjksImV4cCI6MjA2MDY0Mjk2OX0.pLyQDyRaV8ctOEIz-q4XXJp78in7-H3sGVEayOlngZ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);